kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        workingDir: /var/www/html
        ports:
        - containerPort: 80
        volumeMounts:
            - name: data
              mountPath: /var/www/html
              subPath: code
            - name: data
              mountPath: /etc/nginx/conf.d
              subPath: nginx/conf.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc