apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  ports:
  - port: 9000
    targetPort: 9000
  type: NodePort
  selector:
    app: php

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: php:7.2-fpm
        name: php
        workingDir: /var/www/html
        command: ["php-fpm"]
        ports:
        - containerPort: 9000
          name: php
        volumeMounts:
        - name: data
          mountPath: /var/www/html
          subPath: code
        - name: data
          mountPath: /usr/local/etc/php/conf.d
          subPath: php
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
